services:
  backend:
    build: 
      context: .
      dockerfile: ./BE/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  frontend:
    build: 
      context: .
      dockerfile: ./FE/Dockerfile
    ports:
      - "8501:8501"